### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by lxysl** [missuo/bob-plugin-deeplx#1]
更新到1.0.2版本后翻译界面出现未知错误。deeplx版本已更新到0.77且启动
<img width="489" alt="image" src="https://user-images.githubusercontent.com/45818075/226297521-d5be074e-4607-4148-8d39-31fb03d2a743.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/45818075/226297634-9e753fb8-b147-40e8-9c0f-29938742c9f1.png">
<img width="699" alt="image" src="https://user-images.githubusercontent.com/45818075/226297690-6edf4dda-8ba6-4b2a-93d4-9a31b8636503.png">

**Comment by missuo** [comment]
请告知，你翻译的内容是什么？

**Comment by LIZSK** [comment]
你好，我也有同样的问题。尝试多次网页内容翻译显示：未知错误

**Comment by missuo** [comment]
> 你好，我也有同样的问题。尝试多次网页内容翻译显示：未知错误

请不要使用网页内容翻译。我在README里面已经写清楚了。
