### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by w1033775433** [missuo/bob-plugin-deeplx#14]
Once I use Alternatives, three translations appear in Bob, two of which are identical. If I turn it off, only one result appears.
<img width="381" alt="截屏2024-02-05 07 46 51" src="https://github.com/missuo/bob-plugin-deeplx/assets/117188760/8c7fe859-4b13-42ce-944b-3137fa462b70">
<img width="922" alt="截屏2024-02-05 07 49 55" src="https://github.com/missuo/bob-plugin-deeplx/assets/117188760/e9e63c0b-a0cd-4f55-b65a-079eb4b5906e">

<img width="399" alt="截屏2024-02-05 07 52 34" src="https://github.com/missuo/bob-plugin-deeplx/assets/117188760/02c40c77-7a37-40ad-b416-8af9b4b5db1f">

**Comment by missuo** [comment]
The data is provided by DeepL API and we do not do any processing. This is normal, there may not be three alternative results, so there will be duplicates.
