### ISSUE TITLE
A problem seems to have arisen

### ISSUE THREAD

**Issue by w1033775433** [missuo/bob-plugin-deeplx#15]
<img width="399" alt="image" src="https://github.com/missuo/bob-plugin-deeplx/assets/117188760/8748f565-1d06-4e46-8dc9-301d53afb728">

**Comment by missuo** [comment]
<img width="430" alt="image" src="https://github.com/missuo/bob-plugin-deeplx/assets/55200481/829542a7-99ed-4190-acae-866e04620afc">

**Comment by w1033775433** [comment]
What's the cause of this?

**Comment by missuo** [comment]
Are you sure you have correctly installed DeepLX before using the plugin?

**Comment by w1033775433** [comment]
<img width="660" alt="image" src="https://github.com/missuo/bob-plugin-deeplx/assets/117188760/d34d262d-c8ed-4e78-b7e1-b41b12378c7b">

Mine shows the following

**Comment by missuo** [comment]
> <img alt="image" width="660" src="https://private-user-images.githubusercontent.com/117188760/305262338-d34d262d-c8ed-4e78-b7e1-b41b12378c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNDcwODgsIm5iZiI6MTcwODA0Njc4OCwicGF0aCI6Ii8xMTcxODg3NjAvMzA1MjYyMzM4LWQzNGQyNjJkLWM4ZWQtNGU3OC1iN2UxLWI0MWIxMjM3OGM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwMTI2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWYwMDg4NTc1MWI5NjZkNDE2YThmMWFjMTA1YWE0NWZiZDFhYjY5NmE1YjY5ZTI3ZTUzZDdjZjE5YTA2MmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ULItmOEA6jP8Q-oWsy_3AiGiWebvB5BpomZBXynl9pI">
> Mine shows the following

Please do not mindlessly copy all the commands.

**Comment by missuo** [comment]
Please continue to execute the following code.

```bash
brew services start deeplx
```

**Comment by w1033775433** [comment]
Running result: "Service `deeplx` already started, use `brew services restart deeplx` to restart."

**Comment by w1033775433** [comment]
Run “brew services list” and get “Name Status User File deeplx started niujiageng ~/Library/LaunchAgents/homebrew.mxcl.deeplx.plist”
But there is no homebrew.mxcl.deeplx.plist in /Library/LaunchAgents
