### ISSUE TITLE
Deeplx in BOB doesn't work

### ISSUE THREAD

**Issue by harrisonhxy** [missuo/bob-plugin-deeplx#18]
**macOS: 14.5 Sonoma**

**chip: m2**

my deeplx version is the latest， my service looks like normal as well：<img width="585" alt="image" src="https://github.com/user-attachments/assets/3e8665a2-e0a1-403f-805f-2e5038976fef">
thats my service setting in BOB, i didn't change it. But now it doesn't work, it says No response for more than 60 seconds
<img width="710" alt="image" src="https://github.com/user-attachments/assets/ddd3cba9-dccb-4789-9363-ce3f1d634425">

**Comment by missuo** [comment]
It may be a problem with the DeepL official server. 

I will check it later. Thank you for your feedback.

**Comment by missuo** [comment]
It seems impossible to reproduce. @hexiang-yang

**Comment by harrisonhxy** [comment]
> It seems impossible to reproduce. 这似乎不可能重现。@hexiang-yang

This is quite strange. After I changed the deeplx API, the deeplx functionality in BOB started working normally

**Comment by harrisonhxy** [comment]
> > It seems impossible to reproduce. 这似乎不可能重现。@hexiang-yang
> 
> This is quite strange. After I changed the deeplx API, the deeplx functionality in BOB started working normally

btw I have tried to reinstall and update it.

**Comment by missuo** [comment]
Pls check your network.
