### ISSUE TITLE
翻译结果显示多余

### ISSUE THREAD

**Issue by garryde** [missuo/bob-plugin-deeplx#2]
最近升级后会显示alternatives的内容，建议去掉或者在设置中增加开关

<img width="725" alt="image" src="https://user-images.githubusercontent.com/14953698/228067458-56dc086c-05b4-4c02-965e-b699d84ad008.png">

**Comment by missuo** [comment]
使用v1.0.1的插件就没有。

**Comment by missuo** [comment]
@garryde [v1.0.3](https://raw.githubusercontent.com/missuo/bob-plugin-deeplx/main/dist/bob-plugin-deeplx-1.0.3.bobplugin) has been released. Support to enable or disable alternatives in settings. You can update to the latest version directly by checking for updates.

**Comment by garryde** [comment]
Great, many thanks
