### ISSUE TITLE
将文本翻译为中文时失败

### ISSUE THREAD

**Issue by possible318** [missuo/bob-plugin-deeplx#20]
当targetLang 指定为自动或者中文简体时结果返回Unsupported target languages
该问题的原因是在deeplx中

target_lang = zh-hans时
![image](https://github.com/user-attachments/assets/e34f4109-4158-478e-9a31-0e4d4fbd9cf2)

target_lang = auto 时
![image](https://github.com/user-attachments/assets/cb6456f2-deee-40d3-a91b-2ac87e704d02)

target_lang = zh时 运行正常
![image](https://github.com/user-attachments/assets/b0f342f2-bfd3-4888-8104-652ec826aff4)

**Comment by missuo** [comment]
Unable to reproduce

**Comment by missuo** [comment]
<img width="682" alt="image" src="https://github.com/user-attachments/assets/2833de4c-fb57-49eb-9062-5ff0b38e3ff7">
