### ISSUE TITLE
deeplx 503 error

### ISSUE THREAD

**Issue by harrisonhxy** [missuo/bob-plugin-deeplx#23]
The Deeplx plugin on Bob is not working again. But I saw the latest issue on Deeplx, reporting  [error 503](https://github.com/OwO-Network/DeepLX/issues/149). it because of Deeplx's problem that caused Bob to fail?

Thank you for your reply.

**Comment by yikZero** [comment]
# Temporary Fix for DeepLX Bob Plugin Translation Issues

## Background
DeepL has officially discontinued their old API. While the DeepLX author has implemented a temporary fix in v0.9.8.1, some language variant features (like handling zh-Hans/zh-Hant) still need to be restored. [Source](https://github.com/OwO-Network/DeepLX/issues/149#issuecomment-2449101637)

## Steps to Fix

### 1. Update DeepLX to Latest Version
First, update your DeepLX installation to **v0.9.8.1**:
```sh
brew update
brew upgrade deeplx
brew services restart owo-network/brew/deeplx
```

### 2. Add Temporary Language Variant Handling
Add the following code to your Bob plugin's `main.js` to temporarily restore language variant support:

```diff
if (query.from === "auto") {
        sourceLang = lang.langMap.get(query.detectFrom);
    } else {
        sourceLang = lang.langMap.get(query.from);
    }
    let targetLang = "";
    if (query.to === "auto") {
        targetLang = lang.langMap.get(query.detectTo);
    } else {
        targetLang = lang.langMap.get(query.to);
    }
+   // Handle language variants (e.g., zh-Hans, zh-Hant, pt-BR)
+   function normalizeLanguageTarget(originalTargetLang) {
+       // Check if the language code contains a variant identifier "-"
+       const parts = originalTargetLang.split('-');
+       if (parts.length > 1) {
+           // Get base language code and full variant code
+           const baseLang = parts[0].toUpperCase();
+           return {
+               target_lang: baseLang,
+               regional_variant: originalTargetLang
+           };
+       }
+       return {
+           target_lang: originalTargetLang
+       };
+   }
+   // Process target language
+   const normalizedTarget = normalizeLanguageTarget(targetLang);
+   // Construct request body with variant handling
    const body = JSON.stringify({
        text: query.text,
        source_lang: sourceLang,
-       target_lang: targetLang,
+       target_lang: normalizedTarget.target_lang,
+       ...(normalizedTarget.regional_variant && {
+           regional_variant: normalizedTarget.regional_variant
+       })
    });
```

## Note
This is a **temporary** solution while we wait for the DeepLX upstream to restore full language variant handling functionality. Once that's implemented, **this client-side modification won't be necessary anymore**.

**Comment by missuo** [comment]
Fixed.

https://github.com/OwO-Network/DeepLX/commit/9edb997f069eec845cb9aa385290f9fea8894790

https://github.com/OwO-Network/DeepLX/commit/62a993bb13229ced1521d69aad31bba47e957a08

**Comment by missuo** [comment]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/629eb30e-c6fa-4e47-8f00-a5123ba326b3">
