### ISSUE TITLE
英文译中文显示：未知错误

### ISSUE THREAD

**Issue by LIZSK** [missuo/bob-plugin-deeplx#3]
已安装homebrew
开始的时候可以正常使用，在十几次之后就显示未知错误
<img width="380" alt="Screenshot 2023-04-02 at 14 46 46" src="https://user-images.githubusercontent.com/129670832/229356889-fe14763a-c41b-4528-bc43-0feca526bf9e.png">

**Comment by missuo** [comment]
请不要使用 沉浸式翻译那个插件！！！

**Comment by missuo** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/55200481/229357025-70aa41ce-5c0b-434e-9d7d-d862a68d1ef5.png">

**Comment by LIZSK** [comment]
感谢您的回复！我没有安装沉浸式翻译的插件，这次是在便签上进行翻译的，还是同样的提示。
<img width="479" alt="Screenshot 2023-04-02 at 14 52 14" src="https://user-images.githubusercontent.com/129670832/229357190-0771d97d-6c8c-42c1-8a06-1f501954f498.png">

**Comment by missuo** [comment]
> 感谢您的回复！我没有安装沉浸式翻译的插件，这次是在便签上进行翻译的，还是同样的提示。 <img alt="Screenshot 2023-04-02 at 14 52 14" width="479" src="https://user-images.githubusercontent.com/129670832/229357190-0771d97d-6c8c-42c1-8a06-1f501954f498.png">

你当前的IP已经被封锁了。。。请稍候再试，或者更换IP。
