### ISSUE TITLE
homebrew问题

### ISSUE THREAD

**Issue by tai769** [missuo/bob-plugin-deeplx#9]
为什么homebrew源找不到deeplx的包呢是因为源的问题吗

**Comment by missuo** [comment]
```bash
brew tap owo-network/brew
```

**Comment by missuo** [comment]
> 为什么homebrew源找不到deeplx的包呢是因为源的问题吗

[https://github.com/missuo/bob-plugin-deeplx#deploy-deepl-x](https://github.com/missuo/bob-plugin-deeplx#deploy-deepl-x)

Please read the `README` carefully. You need to use the `brew tap` command to add the brew repository of `owo-network` first.
